sudo: required
services:
  - docker

before_install:
  - docker build -t nunoaleixogoncalves/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nunoaleixogoncalves/docker-react npm run test

#aws deploy options region, app name, env name
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-113624506422"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"